# Generated by Django 5.2.5 on 2025-08-13 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=20)),
                ('room_rent', models.TextField()),
                ('facilities', models.TextField()),
                ('rating', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
