# Generated by Django 5.2.5 on 2025-08-22 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_service_provider',
            field=models.BooleanField(default=False),
        ),
    ]
