# Generated by Django 5.2.5 on 2025-08-29 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_booking_car_created_at_car_owner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to='car_pictures/'),
        ),
    ]
